<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <!-- RCL used by both MAUI Blazor Hybrid and Blazor Web -->
    <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm"                          Version="8.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web"            Version="10.0.0" />
    <PackageReference Include="QRCoder"                                        Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aether.Media.AI\Aether.Media.AI.csproj" />
    <ProjectReference Include="..\Aether.Media.Content\Aether.Media.Content.csproj" />
    <ProjectReference Include="..\Aether.Media.Core\Aether.Media.Core.csproj" />
    <ProjectReference Include="..\Aether.Media.Distribution\Aether.Media.Distribution.csproj" />
    <ProjectReference Include="..\Aether.Media.Identity\Aether.Media.Identity.csproj" />
    <ProjectReference Include="..\Aether.Media.LocalLibrary\Aether.Media.LocalLibrary.csproj" />
    <ProjectReference Include="..\Aether.Media.Reel\Aether.Media.Reel.csproj" />
    <ProjectReference Include="..\Aether.Media.Social\Aether.Media.Social.csproj" />
    <ProjectReference Include="..\Aether.Media.Streaming\Aether.Media.Streaming.csproj" />
  </ItemGroup>

</Project>
