<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AetherNet.Media.UI.Shared\AetherNet.Media.UI.Shared.csproj" />
    <ProjectReference Include="..\AetherNet.Media.DependencyInjection\AetherNet.Media.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
